# Generated by Django 3.0.7 on 2020-06-23 11:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('J2D_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='day',
            field=models.DateField(default=datetime.date(2020, 6, 23)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL),
        ),
    ]
