# Generated by Django 3.0.7 on 2020-06-23 13:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('J2D_api', '0002_auto_20200623_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='day',
            field=models.DateField(default=datetime.datetime(2020, 6, 23, 13, 37, 47, 593722, tzinfo=utc)),
        ),
    ]
