# Generated by Django 3.0.7 on 2020-06-23 14:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('J2D_api', '0004_auto_20200623_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='day',
            field=models.DateField(default=datetime.datetime(2020, 6, 23, 14, 0, 45, 313965, tzinfo=utc)),
        ),
    ]
