# Generated by Django 3.0.7 on 2020-06-25 16:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('J2D_api', '0005_auto_20200623_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='day',
            field=models.DateField(default=datetime.datetime(2020, 6, 25, 16, 34, 6, 268847, tzinfo=utc)),
        ),
    ]
