# Generated by Django 3.0.7 on 2020-07-01 13:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('J2D_api', '0006_auto_20200625_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='day',
            field=models.DateField(default=datetime.datetime(2020, 7, 1, 13, 0, 15, 911405, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='ItemList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=False)),
                ('list_rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='J2D_api.ItemList')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_lists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
